host: 192.162.244.128 # IP-адрес сервера
port: 25759 # Порт сервера
proxy: SOCKS # Тип используемых прокси | SOCKS, HTTP, BOTH, NONE
duration: 300 # Длительность атаки | секунды
threads: 200 # Количество потоков для отправки ботов | Потоки запускаются со скоростью: 20/сек
delay: 200 # Задержка отправки ботов для каждого потока | миллисекунды
nicks: LIST # Тип ников | LIST, ALTS или RANDOM
listen: true # Отслеживать состояние бота и иметь возможность осуществлять действия
ping: true # Активировать модуль спама пинг-пакетами
join: true # Активировать модуль спама ботами
chat: true # Выводить чат сервера
info: 0 # Способ вывода информации | 0 или 1
stay: true # Удерживать ботов на сервере
actions: # Выполнять определённые действия на сервере | количество_выполнений;задержка;действие;аргументы
  - 1;2000;chat;/register qwerty12345 qwerty12345
  - 1;3000;chat;/login qwerty12345
  - 2;3500;move;true
  - 5;4000;use;MAIN_HAND
  - 3;4000;use;OFF_HAND
  - 1;4500;chat;!Боты стоят на прокси серверах, их нету смысла даже банить
  - 1;5000;chat;!Если вы попытаетесь забанить по айпи любого из бота у вас не чего не получится, боты еще будут
  - 1;5100;chat;!Самый ахуенный кодер TheSocrum and Zakladhik
  - 1;5200;chat;!Автор этой всей поебни TheSocrum
  - 1;5300;chat;!Боты стоят на прокси серверах, их нету смысла даже банить
  - 1;5400;chat;!Если вы попытаетесь забанить по айпи любого из бота у вас не чего не получится, боты еще будут
  - 1;5500;chat;!Самый ахуенный кодер TheSocrum and Zakladhik
  - 1;5600;chat;!Автор этой всей поебни TheSocrum
  - 1;5700;chat;!Боты стоят на прокси серверах, их нету смысла даже банить
  - 1;5800;chat;!Если вы попытаетесь забанить по айпи любого из бота у вас не чего не получится, боты еще будут
  - 1;5900;chat;!Самый ахуенный кодер TheSocrum and Zakladhik
  - 1;6000;chat;!Автор этой всей поебни TheSocrum
  - 1;6100;chat;!Боты стоят на прокси серверах, их нету смысла даже банить
  - 1;6200;chat;!Если вы попытаетесь забанить по айпи любого из бота у вас не чего не получится, боты еще будут
  - 1;6300;chat;!Самый ахуенный кодер TheSocrum and Zakladhik
  - 1;6400;chat;!Автор этой всей поебни TheSocrum
  - 1;6500;chat;!Боты стоят на прокси серверах, их нету смысла даже банить
  - 1;6600;chat;!Если вы попытаетесь забанить по айпи любого из бота у вас не чего не получится, боты еще будут
  - 1;6700;chat;!Самый ахуенный кодер TheSocrum and Zakladhik
  - 1;6800;chat;!Автор этой всей поебни TheSocrum
  - 1;6900;chat;!Боты стоят на прокси серверах, их нету смысла даже банить